[package]
name = "ex_tiktoken"
version = "0.1.1"
authors = []
edition = "2021"

[lib]
name = "ex_tiktoken"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
tiktoken-rs = "0.4.2"
